### PR TITLE
Update pty.js

### PR DESCRIPTION
**Pull request by svenax**
Fixes installation problem in Atom 1.2.0.

### CODE REVIEW

**Comment by K4zuki** [comment]
:+1: 
it works under:
**Ubuntu 14.04LTS**
**Atom 1.2.3**

What I did is:
```
git clone https://github.com/f/atom-term2
cd atom-term2/
apm install
rm -rf /home/(username)/.atom/packages/term2 (in my case the directory was not empty)
sudo apm link .
```

**Comment by Sterbic** [comment]
Works on OSX 10.11.1 and Atom 1.2.3.

**Comment by neopostmodern** [comment]
Above instructions to install didn't work, but this did:
```
git clone https://github.com/svenax/atom-term2.git
cd atom-term2
git checkout update-pty.js 
apm install
sudo apm link .
```

**Comment by robneu** [comment]
:+1: works on OSX `10.11.1 (15B42)` and Atom `1.2.4`

**Comment by lorenzos** [comment]
Works for mee to, on Xubuntu 15.10 and last version of Atom.

Waiting for the merge, so I can install the plugin on all my workstations: I use a settings sync package and obviously I cannot tell it to grab the package from a different repo/fork other than the original published one.

**Comment by sergiolepore** [comment]
It works! OS X 10.11.1, Atom 1.2.4. cc @f

**Comment by oXis** [comment]
Worked for me, Linux Mint 17.2
Instead of linking, I just moved what was inside atom-term2/ into .atom/packages/term2/

**Comment by dustinblackman** [comment]
Can we get this merged?

**Comment by sergiolepore** [comment]
@dustinblackman this repo appears to be dead/abandoned :confused:

**Comment by TomSta** [comment]
K4zuki's solution worked for me, thank you :)

**Pull request merged**
