### PR TITLE
term3 fork...

### PR DESCRIPTION
**Pull request by MoOx**
@kans created a fork but did not create a PR and instead published a term3 package. @kans any particular reason to act this way?
This sounds a bit silly as term2 should have been a PR to term in the first place. Maybe we should consider unify effort... ?

### CODE REVIEW

**Comment by kans** [comment]
@MoOx 
Collaboration sounds great!  I'd honestly much rather push everything back upstream and kill T3 - that was the original plan.  

The major difference between the two is that t3 adds the ability to drive terminals from other packages - ie, you can stream data into stin and out of stdout.  Floobits uses the api to "share" terminals.  To support this feature, some terminals don't fork a shell - they are just dumb ptys that generate html.  

Floobits has the general policy that commits should reflect the process of work instead of its output - ie, commits that go down the wrong path or don't work are not rebased away.  If you are still interested in these changes for t2, I'd be happy to submit piecemeal PRs that don't dirty your history.  Also, how do you feel about adding react as a dependency?

**Comment by MoOx** [comment]
For my concern, I love react and use it everyday since I am a front-end developer :)
No problem for me for the current history.

@f what do you think ?

**Comment by f** [comment]
@kans Thanks for this huge effort! I can give you the push permission since you had awesome improvements on it. What do you think @MoOx?

C'mon guys, this is open source. Let's make this magic happen, let's unify our powers, not divide :)

**Comment by kans** [comment]
@f 
Thanks for the vote of confidence.  I plan to port most changes over to term2 and shut down term3.

**Comment by kans** [comment]
@f 
Would you add me to atom-term.js as well.  There are a couple of critical fixes I'd like to commit.

**Comment by MoOx** [comment]
Maybe we should also think to backport atom-term.js changes to original term.js ? poke @chjj

**Pull request closed without merging**
